# Generated by Django 5.2.7 on 2025-12-09 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iva', '0001_initial'),
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AsientoInversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('tipo_asiento', models.CharField(choices=[('A', 'Aporte'), ('C', 'Compensación'), ('R', 'Retiro')], default='A', max_length=1)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tesoreria.registro')),
                ('inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.inversor')),
            ],
        ),
        migrations.CreateModel(
            name='PorcentajeInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inversor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inversiones.inversor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iva.clienteproyecto')),
            ],
            options={
                'unique_together': {('inversor', 'proyecto')},
            },
        ),
    ]
