# Generated by Django 5.2.7 on 2026-01-26 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0001_initial'),
        ('iva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientoinversor',
            options={'verbose_name': 'Asiento de Inversor', 'verbose_name_plural': 'Asientos de Inversores'},
        ),
        migrations.AlterModelOptions(
            name='inversor',
            options={'verbose_name': 'Inversor', 'verbose_name_plural': 'Inversores'},
        ),
        migrations.AlterModelOptions(
            name='porcentajeinversion',
            options={'verbose_name': 'Porcentaje de Inversión', 'verbose_name_plural': 'Porcentajes de Inversión'},
        ),
        migrations.CreateModel(
            name='PorcentajeGastosInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mes', models.IntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iva.clienteproyecto')),
            ],
            options={
                'verbose_name': 'Porcentaje de alocación de Gastos de Inversión',
                'verbose_name_plural': 'Porcentajes de alocación de Gastos de Inversión',
                'unique_together': {('proyecto', 'mes')},
            },
        ),
    ]
