# Generated by Django 5.2.7 on 2025-12-09 13:04

import django.core.validators
import django.db.models.deletion
import iva.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_proyecto', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Imputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imputacion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadDeNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_de_negocio', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_documento', models.DateField()),
                ('serie', models.SmallIntegerField(default=0)),
                ('numero', models.IntegerField()),
                ('añomes_imputacion_gasto', models.IntegerField()),
                ('añomes_imputacion_contable', models.IntegerField(default=202509, validators=[django.core.validators.MinValueValidator(202001), django.core.validators.MaxValueValidator(209912)])),
                ('tiene_cno', models.BooleanField(default=False)),
                ('concepto', models.CharField(max_length=100)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('impuestos_retidos', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to=iva.models.Documento.ruta_archivo)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('imputado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('cliente_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iva.clienteproyecto')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shared.moneda')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared.municipio')),
                ('imputacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iva.imputacion')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'Cargado'), (2, 'Modificado'), (3, 'Pagado'), (4, 'Eliminado'), (5, 'Restaurado')], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iva.documento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentos_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor_receptor', models.IntegerField(choices=[(1, 'Proveedor'), (2, 'Receptor')], default=1)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('cbu_alias', models.CharField(blank=True, max_length=35, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('imputacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iva.imputacion')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['nombre_fantasia'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_documento', to='iva.persona'),
        ),
        migrations.AddField(
            model_name='documento',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptor_documento', to='iva.persona'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iva.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='unidad_de_negocio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iva.unidaddenegocio'),
        ),
        migrations.AddField(
            model_name='clienteproyecto',
            name='unidad_de_negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='iva.unidaddenegocio'),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('tipo_documento', 'serie', 'numero', 'proveedor', 'activo')},
        ),
    ]
