# Generated by Django 5.2.7 on 2025-12-09 13:04

import datetime
import django.db.models.deletion
import simple_history.models
import tesoreria.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iva', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DbPresupuestosV2',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('proveedor_id', models.IntegerField(db_column='Proveedor ID')),
                ('proveedor', models.CharField(db_column='Proveedor', max_length=255)),
                ('cliente_proyecto_id', models.IntegerField(db_column='Cliente/Proyecto ID')),
                ('cliente_proyecto', models.CharField(db_column='Cliente/Proyecto', max_length=255)),
                ('observacion', models.TextField(db_column='Observacion')),
                ('nombre', models.CharField(db_column='Nombre', max_length=765)),
                ('monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=15)),
                ('saldo', models.DecimalField(db_column='Saldo', decimal_places=2, max_digits=15)),
                ('estado', models.IntegerField(choices=[(1, 'Cargado'), (2, 'Aprobado'), (3, 'Completo'), (4, 'Excedido'), (5, 'Ampliado'), (99, 'Rechazado'), (101, 'Inactivo')], db_column='Estado', default=1)),
                ('aprobado', models.IntegerField(choices=[(1, 'No aprobado'), (2, 'Aprobado'), (3, 'Rechazado')], db_column='Aprobado', default=1)),
            ],
            options={
                'db_table': 'db_presupuestos_v2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DolarMEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('compra', models.DecimalField(decimal_places=2, max_digits=20)),
                ('venta', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubImputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sub Imputación',
                'verbose_name_plural': 'Sub Imputaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('dueño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shared.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('neto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('observacion', models.CharField(max_length=100, null=True)),
                ('numero', models.IntegerField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('activo', models.BooleanField(default=True)),
                ('cliente_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iva.clienteproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndiceCAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('indice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Índice CAC',
                'verbose_name_plural': 'Índices CAC',
                'ordering': ['-año', '-mes'],
                'unique_together': {('mes', 'año')},
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_reg', models.CharField(choices=[('OP', 'Orden de Pago'), ('REC', 'Recibo'), ('FC', 'Factura de compra'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('MC', 'Movimiento entre cuentas'), ('CH', 'Cheque'), ('PSF', 'Pago sin factura'), ('DEP', 'Depósito'), ('ISF', 'Ingreso sin factura'), ('RETH', 'Retención hecha'), ('RETS', 'Retención sufrida'), ('AJU', 'Ajuste de caja'), ('FCV', 'Factura de venta'), ('PERCS', 'Percepción sufrida'), ('PERCH', 'Percepción hecha'), ('RECFC', 'Factura de venta con recibo'), ('OPFC', 'Factura de compra con OP')], max_length=5)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cliente_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iva.clienteproyecto')),
                ('imputacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iva.imputacion')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iva.persona')),
                ('unidad_de_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iva.unidaddenegocio')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('observacion', models.TextField(null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Cargado'), (2, 'Aprobado'), (3, 'Completo'), (4, 'Excedido'), (5, 'Ampliado'), (99, 'Rechazado'), (101, 'Inactivo')], default=1)),
                ('aprobado', models.IntegerField(choices=[(1, 'No aprobado'), (2, 'Aprobado'), (3, 'Rechazado')], default=1)),
                ('activo', models.BooleanField(default=True)),
                ('archivos', models.ManyToManyField(blank=True, related_name='presupuestos', related_query_name='presupuestos', to='tesoreria.archivo')),
                ('cliente_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iva.clienteproyecto')),
                ('comentarios', models.ManyToManyField(blank=True, to='tesoreria.comentario')),
                ('imputacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iva.imputacion')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iva.persona')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.IntegerField(choices=[(1, 'Cargado'), (2, 'Aprobado'), (3, 'Completo'), (4, 'Excedido'), (5, 'Ampliado'), (99, 'Rechazado'), (101, 'Inactivo')], default=1)),
                ('observacion', models.CharField(max_length=100, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estados', to='tesoreria.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reg', models.CharField(choices=[('OP', 'Orden de Pago'), ('REC', 'Recibo'), ('FC', 'Factura de compra'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('MC', 'Movimiento entre cuentas'), ('CH', 'Cheque'), ('PSF', 'Pago sin factura'), ('DEP', 'Depósito'), ('ISF', 'Ingreso sin factura'), ('RETH', 'Retención hecha'), ('RETS', 'Retención sufrida'), ('AJU', 'Ajuste de caja'), ('FCV', 'Factura de venta'), ('PERCS', 'Percepción sufrida'), ('PERCH', 'Percepción hecha'), ('RECFC', 'Factura de venta con recibo'), ('OPFC', 'Factura de compra con OP')], max_length=5)),
                ('fecha_reg', models.DateField()),
                ('nro_documento', models.CharField(blank=True, max_length=75, null=True)),
                ('añomes_imputacion', models.BigIntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('monto_gasto_ingreso_neto', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('iva_gasto_ingreso', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('monto_op_rec', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('tipo_de_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('realizado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('numero_cheque', models.CharField(blank=True, max_length=20, null=True)),
                ('archivos', models.ManyToManyField(blank=True, related_name='registros', related_query_name='registros', to='tesoreria.archivo')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tesoreria.caja')),
                ('caja_contrapartida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tesoreria.caja')),
                ('certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tesoreria.certificadoobra')),
                ('cliente_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='iva.clienteproyecto')),
                ('documento', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='iva.documento')),
                ('imputacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='iva.imputacion')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared.moneda')),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tesoreria.presupuesto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='iva.persona')),
                ('unidad_de_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='iva.unidaddenegocio')),
                ('sub_imputacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tesoreria.subimputacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('op', models.FileField(blank=True, null=True, upload_to='documentos/op/')),
                ('documentos', models.ManyToManyField(blank=True, related_name='pago_factura', to='iva.documento')),
                ('registros_fc', models.ManyToManyField(blank=True, related_name='factura_fc', to='tesoreria.registro')),
                ('registros_pago', models.ManyToManyField(blank=True, related_name='pago_factura', to='tesoreria.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Echeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('acreditado', models.BooleanField(default=False)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tesoreria.registro')),
            ],
        ),
        migrations.CreateModel(
            name='ConciliacionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tesoreria.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('ultimo_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tesoreria.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=tesoreria.models.Retencion.ruta_archivo)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField(default=datetime.date(2025, 12, 9))),
                ('tipo', models.CharField(default='IIGG', max_length=10)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tesoreria.registro')),
                ('registro_fc', models.ManyToManyField(blank=True, related_name='retencion_fc', to='tesoreria.registro')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tesoreria.caja')),
                ('registro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tesoreria.registro')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRegistro',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_reg', models.CharField(choices=[('OP', 'Orden de Pago'), ('REC', 'Recibo'), ('FC', 'Factura de compra'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('MC', 'Movimiento entre cuentas'), ('CH', 'Cheque'), ('PSF', 'Pago sin factura'), ('DEP', 'Depósito'), ('ISF', 'Ingreso sin factura'), ('RETH', 'Retención hecha'), ('RETS', 'Retención sufrida'), ('AJU', 'Ajuste de caja'), ('FCV', 'Factura de venta'), ('PERCS', 'Percepción sufrida'), ('PERCH', 'Percepción hecha'), ('RECFC', 'Factura de venta con recibo'), ('OPFC', 'Factura de compra con OP')], max_length=5)),
                ('fecha_reg', models.DateField()),
                ('nro_documento', models.CharField(blank=True, max_length=75, null=True)),
                ('añomes_imputacion', models.BigIntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('monto_gasto_ingreso_neto', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('iva_gasto_ingreso', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('monto_op_rec', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('tipo_de_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('realizado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('numero_cheque', models.CharField(blank=True, max_length=20, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('caja', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tesoreria.caja')),
                ('caja_contrapartida', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)ss', to='tesoreria.caja')),
                ('certificado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)ss', to='tesoreria.certificadoobra')),
                ('cliente_proyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)ss', to='iva.clienteproyecto')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('imputacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)ss', to='iva.imputacion')),
                ('moneda', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shared.moneda')),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)ss', to='iva.persona')),
                ('unidad_de_negocio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)ss', to='iva.unidaddenegocio')),
                ('presupuesto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)ss', to='tesoreria.presupuesto')),
                ('sub_imputacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)ss', to='tesoreria.subimputacion')),
            ],
            options={
                'verbose_name': 'historical registro',
                'verbose_name_plural': 'historical registros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Leida'), (3, 'Completada')], default=1)),
                ('link_to', models.CharField(default=None, max_length=100, null=True)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tesoreria.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='SubImputacionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imputacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_imputacion_mappings', to='iva.imputacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_imputacion_mappings', to='iva.persona')),
                ('sub_imputacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='tesoreria.subimputacion')),
            ],
            options={
                'verbose_name': 'Mapeo de Sub Imputación',
                'verbose_name_plural': 'Mapeos de Sub Imputación',
                'ordering': ['id'],
                'unique_together': {('proveedor', 'imputacion')},
            },
        ),
    ]
