# Generated by Django 5.2.7 on 2026-01-26 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencion',
            name='fecha',
            field=models.DateField(default=datetime.date(2026, 1, 26)),
        ),
    ]
