# Generated by Django 5.2.7 on 2026-01-27 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_alter_retencion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolarmep',
            name='compra',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dolarmep',
            name='venta',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='retencion',
            name='fecha',
            field=models.DateField(default=datetime.date(2026, 1, 27)),
        ),
    ]
